config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root to: 'welcome#index'

  get 'r/:code', to: 'offers#recruit', as: :offer_recruit
  resources :offers, except: [:show, :update, :destroy]
  resources :payables do
    resources :payments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :users, dependent: :nullify
  has_one :payable, dependent: :destroy

  validates_presence_of :user, :price, :percentage

  before_create :generate_code
  after_create :generate_payable

  PRICES = [10000, 50000, 100000, 500000, 1000000, 5000000]
  PERCENTAGES = [10, 20, 30, 40, 50, 60, 70, 80, 90]

  def code
    if payable.paid?
      super
    else
      nil
    end
  end

  private

  def payable_amount
    price/100*percentage
  end

  def generate_code
    self.code = SecureRandom.urlsafe_base64(32)
  end

  def generate_payable
    create_payable(amount: payable_amount, user: user)    
  end
end

app/models/payable.rb
class Payable < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  has_many :payments, dependent: :destroy

  validates_presence_of :user, :offer, :amount

  after_update :generate_transaction

  def pay
    self.paid = true
    self.save
  end

  private

  def generate_transaction
    if paid
      user.credits.create(to: user.predecessor, amount: amount)
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :payable

  validates_presence_of :user, :payable

  enum status: [:initialized, :pending, :unpaid, :paid, :cancelled]
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :from, polymorphic: true
  belongs_to :to, polymorphic: true

  validates_presence_of :from, :to, :amount
  before_create :calculate_portion
  after_create :pay_predecessor

  private

  def portion
    [amount/100*(from.offer.percentage), amount/100*(100-from.offer.percentage)]
  end

  def calculate_portion
    self.amount = portion.first
  end

  def pay_predecessor
    if to.present? && portion.first > 100
      to.credits.create(to: to.predecessor, amount: portion.last)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :offers, dependent: :nullify
  has_many :payables, dependent: :nullify
  has_many :payments, dependent: :nullify
  has_many :deposits, class_name: 'Transaction', as: 'to'
  has_many :credits, class_name: 'Transaction', as: 'from'

  def offer
    if offer_id
      Offer.find(offer_id)
    end
  end

  def predecessor
    offer.user if offer
  end

  def name
    email.split('@').first.humanize
  end

  def hash
    Digest::MD5.hexdigest("#{id}_#{email}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @deposits = current_user.deposits
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!, except: [:recruit]

  def index
    @offers = current_user.offers
  end

  def recruit
    @offer = Offer.find_by(code: params[:code])
    session[:offer_code] = @offer.code
    redirect_to new_user_registration_path
  end

  def new
    @offer = current_user.offers.new
  end

  def create
    @offer = current_user.offers.new(offer_params)
    respond_to do |format|
      if @offer.save
        format.html { redirect_to offers_path }
      else
        format.html { redirect_to new_offer_path }
      end
    end
  end

  private 

  def set_offer
    @offer = current_user.offers.find params[:id] 
  end

  def offer_params
    params.require(:offer).permit(:price, :percentage)
  end
end

app/controllers/payables_controller.rb
class PayablesController < ApplicationController
  before_action :authenticate_user!

  def show
    @payable = current_user.payables.find(params[:id])
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payable

  def create
    @payment = @payable.payments.new(user: current_user)
    respond_to do |format|
      if @payment.save && @payable.pay
        format.html { redirect_to offers_path }
      else
        format.html { render json: @payment.errors }
      end
    end
  end

  private

  def set_payable
    @payable = current_user.payables.find(params[:payable_id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    session[:return_to] = params[:return_to] if params[:return_to]
    super
  end

  # POST /resource/sign_in
  def create
    super do |user|
      if user
        session[:user_id] = user.id
        if session[:return_to]
          redirect_to session[:return_to]
          session[:return_to] = nil
        else
          redirect_to root_url
        end
        return
      end
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api/credentials_helper.rb
module Api::CredentialsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/oauth/applications_helper.rb
module Oauth::ApplicationsHelper
end

app/helpers/oauth_applications_helper.rb
module OauthApplicationsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
  def percentage_options
    Offer::PERCENTAGES.map { |e| ["#{e}%", e] }
  end

  def price_options
    if current_user.offer.present?
      limit = current_user.offer.price
      Offer::PRICES.select{ |e| e <= limit }.map { |e| ["RM #{e/100}", e] }
    else
      Offer.PRICES
    end
  end
end

app/helpers/payables_helper.rb
module PayablesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/offers/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col s12 m12 l12">
        <h2>My Offers</h2>
      </div>
    </div>
    <div class="row">
      <div class="col s12 m12 l12">
        <table>
          <thead>
            <tr>
              <th>Price</th>
              <th>%</th>
              <th>Paid</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @offers.each do |offer| %>
              <tr>
                <td><%= offer.price/100 %></td>
                <td><%= offer.percentage %></td>
                  <% if offer.payable.paid %>
                    <td><i class="material-icons green-text">done</i></td>
                    <td>
                      <input type="text" value="<%= offer_recruit_url(offer.code) %>" id="offerCode<%= offer.id %>">
                      <%#= link_to 'Copy', '', class: 'btn clipboard-btn waves-effect waves-light', data: { "clipboard-action": "copy", "clipboard-target": "#offerCode#{offer.id}" } %>
                    </td>
                  <% else %>
                    <td><i class="material-icons grey-text text-lighten-2">done</i></td>
                    <td><%= link_to 'Pay now', payable_payments_path(offer.payable), method: :post, class: 'btn waves-effect waves-light orange' %></td>
                  <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="fixed-action-btn">
    <%= link_to new_offer_path, class: 'btn-floating btn-large waves-effect waves-light' do %>
      <i class="large material-icons">add</i>
    <% end %>
  </div>
</main>

app/views/offers/new.html.erb
<main>
  <div class="container">
    <h2>New Offer</h2>
    <%= form_for(@offer) do |f| %>

      <div class="row">
        <div class="col s12 m5 l4">
          <div class="input-field">
            <%= f.select("price", price_options, { prompt: 'Price' }) %>
          </div>
        </div>
        <div class="col s12 m5 l4">
          <div class="input-field">
            <%= f.select("percentage", percentage_options, { prompt: 'Percentage' }) %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col s12 m5 l4">
          <div class="payable">
            <h1>RM <strong class="indigo-text" id="payable_amount">0</strong></h1>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col s12 m12 l12">
          <p>You don't have to pay now</p>
        </div>
      </div>

      <div class="row">
        <div class="col s12 m5 l4">
          <div class="input-field">
            <%= submit_tag "Create", class: "btn" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</main>
  

app/views/payables/show.html.erb
<main>
  <div class="container">
    <%= link_to 'Pay using Paypal', payable_payments_path(@payable), method: :post, class: 'btn btn-large orange' %>
  </div>
</main>